---
title: "formulaic"
output: rmarkdown::html_vignette
author: " "
date: "`r Sys.time()`"
vignette: >
  %\VignetteIndexEntry{formulaic}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---
```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  message = FALSE,
  warning = FALSE,
  error = FALSE,
  comment = "#>"
)
tools::compactPDF(paths = "../vignettes/",
                  qpdf = Sys.which(Sys.getenv("R_QPDF", "qpdf")),
                  gs_quality = 'ebook')
```

```{r setup}
library(formulaic)
library(data.table)
data(snack.dat, package = "formulaic")
```

```{r constant}
outcome.name.awareness <- "Awareness"
outcome.name.satisfaction <- "Satisfaction"

input.names <- c("Age", "Gender", "Income", "Region", "Persona", "Typo")
input.patterns <- c("User", "BP_", outcome.name.awareness, outcome.name.satisfaction)

reduce <- FALSE
max.input.categories = 20
max.outcome.categories.to.search = 4
order.as = "as.specified" 
include.backtick = "as.needed"
format.as = "formula"
```

## Data : snack.dat
To explore the basic function of formulaic, we’ll use snack.dat, a randomly generated data. This dataset contains 23000 observation and 23 columns. This data contains information from the (fictionalized) marketing survey’s data.
```{r snack.dat}
dim(snack.dat)
names(snack.dat)
```

## add.backtick
```{r add.backtick}
formulaic:::add.backtick(x = names(snack.dat))

```

```{r create.formula examples}
form.1 <- create.formula(outcome.name = outcome.name.awareness, input.names = NA, input.patterns = NA, dat = snack.dat)

form.2 <- create.formula(outcome.name = outcome.name.awareness, input.names = ".", input.patterns = NA, dat = snack.dat)


form.3 <- create.formula(outcome.name = outcome.name.awareness, input.names = input.names, input.patterns = NA, dat = NA, reduce = reduce, max.input.categories = max.input.categories, max.outcome.categories.to.search = max.outcome.categories.to.search, order.as = order.as, include.backtick = include.backtick, format.as = "character")

form.4 <- create.formula(outcome.name = outcome.name.awareness, input.names = input.names, input.patterns = input.patterns, dat = snack.dat, reduce = reduce, max.input.categories = max.input.categories, max.outcome.categories.to.search = max.outcome.categories.to.search, order.as = order.as, include.backtick = include.backtick, format.as = format.as)


form.5 <- create.formula(outcome.name = outcome.name.awareness, input.names = input.names, input.patterns = input.patterns, dat = snack.dat, reduce = TRUE, max.input.categories = max.input.categories, max.outcome.categories.to.search = max.outcome.categories.to.search, order.as = order.as, include.backtick = include.backtick, format.as = format.as)

form.6 <- create.formula(outcome.name = outcome.name.satisfaction, input.names = input.names, input.patterns = input.patterns, dat = snack.dat, reduce = TRUE, max.input.categories = max.input.categories, max.outcome.categories.to.search = max.outcome.categories.to.search, order.as = order.as, include.backtick = include.backtick, format.as = format.as)

```

```{r reduce.existing.formula examples}
form.7 <- reduce.existing.formula(the.initial.formula = form.3$formula, dat = snack.dat, format.as = "character")

form.8 <- reduce.existing.formula(the.initial.formula = form.4$formula, dat = snack.dat, format.as = "formula")

```
