name: R CMD Check 
on: 
  pull_request:
    branches: 
      - master
  push: 
    branches: 
      - master 

jobs:
  build:

    strategy:
       matrix:
         os: [windows-latest, macOS-latest, ubuntu-16.04]
         r: [devel,3.6, 3.5,3.4, 3.3, 3.2]
         
    runs-on: ${{matrix.os}}
    name: use r ${{matrix.r}}
    
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
        with:
          r-version: ${{matrix.r}} 
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
      - name: Check
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}
    
    
        
    
